# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [30]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
fields = {'BusinessName':1, 'BusinessType':1, 'LocalAuthorityName':1, 'RatingValue': 1, 'scores.Hygiene' : 1, 'scores.Structural' : 1, 'scores.ConfidenceInManagement' : 1, 'geocode.longitude':1, 'geocode.latitude':1}

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print(f'Number of establishments with a hygiene score of 20: {count}')

# Display the first document in the results using pprint
results = establishments.find_one(query, fields)
print("First document with a hygiene score of 20:")
pprint(results or "No documents found with a hygiene score of 20.")

Number of establishments with a hygiene score of 20: 41
First document with a hygiene score of 20:
{'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'LocalAuthorityName': 'Eastbourne',
 'RatingValue': 0,
 '_id': ObjectId('666fa2ba635b43e663fb0aed'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [31]:
# Convert the result to a Pandas DataFrame
hygiene_doc = list(establishments.find(query, fields))
hygiene_df = pd.DataFrame(hygiene_doc)
# Display the number of rows in the DataFrame
rows = hygiene_df.shape[0]
print(f'Number of rows: {rows}')
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows: 41

,_id,BusinessName,BusinessType,RatingValue,LocalAuthorityName,scores,geocode
0,666fa2ba635b43e663fb0aed,The Chase Rest Home,Caring Premises,0,Eastbourne,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...","{'longitude': 0.27694, 'latitude': 50.769705}"
1,666fa2ba635b43e663fb0e6e,Brenalwood,Caring Premises,0,Tendring,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...","{'longitude': 1.278721, 'latitude': 51.857536}"
2,666fa2ba635b43e663fb1177,Melrose Hotel,Hotel/bed & breakfast/guest house,0,Tendring,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...","{'longitude': 1.15927, 'latitude': 51.789429}"
3,666fa2ba635b43e663fb1366,Seaford Pizza,Takeaway/sandwich shop,1,Lewes,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...","{'longitude': 0.10202, 'latitude': 50.770885}"
4,666fa2ba635b43e663fb1379,Golden Palace,Restaurant/Cafe/Canteen,1,Lewes,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...","{'longitude': 0.101446, 'latitude': 50.770724}"
5,666fa2ba635b43e663fb1d1d,Ashby's Butchers,Retailers - other,0,Southend-On-Sea,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...","{'longitude': 0.736349, 'latitude': 51.541448}"
6,666fa2ba635b43e663fb1f34,South Sea Express Cuisine,Restaurant/Cafe/Canteen,0,Southend-On-Sea,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...","{'longitude': 0.7121671, 'latitude': 51.5350065}"
7,666fa2ba635b43e663fb345e,Golden Palace,Takeaway/sandwich shop,0,Rochford,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...","{'longitude': 0.602364, 'latitude': 51.591515}"
8,666fa2ba635b43e663fb38a0,The Tulip Tree,Restaurant/Cafe/Canteen,1,Sevenoaks,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...","{'longitude': 0.146449998021126, 'latitude': 5..."
9,666fa2ba635b43e663fb40b6,F & S,Retailers - other,0,Basildon,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...","{'longitude': 0.462307, 'latitude': 51.57005}"

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [41]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'LocalAuthorityName': {'$regex': '.*London.*'}, 'RatingValue': {'$gte': 4}}
fields = {'BusinessName':1, 'BusinessType':1, 'LocalAuthorityName':1, 'RatingValue': 1, 'scores.Hygiene' : 1, 'scores.Structural' : 1, 'scores.ConfidenceInManagement' : 1, 'geocode.longitude':1, 'geocode.latitude':1}                                                  

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print(f'London establishments with a rating >= 4: {count}')
# Display the first document in the results using pprint
results = establishments.find_one(query, fields)
print("First document of London establishment with a rating >= 4:")
pprint(results)

London establishments with a rating >= 4: 33
First document of London establishment with a rating >= 4:
{'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'LocalAuthorityName': 'City of London Corporation',
 'RatingValue': 4,
 '_id': ObjectId('666fa2ba635b43e663fb2504'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [42]:
# Convert the result to a Pandas DataFrame
london_rating_doc = list(establishments.find(query, fields))
london_rating_df = pd.DataFrame(london_rating_doc)

# Display the number of rows in the DataFrame
rows = london_rating_df.shape[0]
print(f'Number of rows: {rows}')

# Display the first 10 rows of the DataFrame
london_rating_df.head(10)

Number of rows: 33

,_id,BusinessName,BusinessType,RatingValue,LocalAuthorityName,scores,geocode
0,666fa2ba635b43e663fb2504,Charlie's,Other catering premises,4,City of London Corporation,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...","{'longitude': 0.508551, 'latitude': 51.369321}"
1,666fa2ba635b43e663fb2830,Mv City Cruises Erasmus,Other catering premises,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.249255999922752, 'latitude': 5..."
2,666fa2ba635b43e663fb3379,Benfleet Motor Yacht Club,Other catering premises,4,City of London Corporation,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.561954, 'latitude': 51.543831}"
3,666fa2ba635b43e663fb4177,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.346336990594864, 'latitude': 5..."
4,666fa2ba635b43e663fb417c,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.346325, 'latitude': 51.464078}"
5,666fa2ba635b43e663fb4880,Mv Valulla,Other catering premises,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.287555, 'latitude': 51.504071}"
6,666fa2bb635b43e663fb69a2,Tereza Joanne,Other catering premises,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.069286, 'latitude': 51.501121}"
7,666fa2bb635b43e663fb6d56,Brick Lane Brews,Restaurant/Cafe/Canteen,4,City of London Corporation,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...","{'longitude': 0.048006, 'latitude': 51.503733}"
8,666fa2bb635b43e663fb6d71,The Nuance Group (UK) Limited,Retailers - other,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.047966, 'latitude': 51.504112}"
9,666fa2bb635b43e663fb6d72,WH Smith,Retailers - other,5,City of London Corporation,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0479655750095844, 'latitude': ..."

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [45]:
# Long and Lat for Penang Flavours
query = {'BusinessName': 'Penang Flavours'}
fields = {'BusinessName': 1, 'geocode.longitude': 1, 'geocode.latitude': 1}
results = establishments.find_one(query,fields)
pprint(results)

{'BusinessName': 'Penang Flavours',
 '_id': ObjectId('667357e1041028fe9a174b1b'),
 'geocode': {'latitude': 51.490142, 'longitude': 0.08384}}

In [51]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.490142
longitude = 0.08384

query = {
    "RatingValue": 5,
    "geocode": {
        "$geoWithin": {
            "$box": [
                [longitude - degree_search, latitude - degree_search],
                [longitude + degree_search, latitude + degree_search] 
            ]
        }
    }
}

fields = fields = {'BusinessName':1, 'BusinessType':1, 'LocalAuthorityName':1, 'RatingValue': 1, 'scores.Hygiene' : 1, 'scores.Structural' : 1, 'scores.ConfidenceInManagement' : 1, 'geocode.longitude':1, 'geocode.latitude':1}
sort = [('scores.Hygiene', 1)]
limit = 5

results = list(establishments.find(query,fields).sort(sort).limit(limit))
# Print the results
print(f'Found {len(results)} establishments:')
for result in results:
    pprint(result)

Found 5 establishments:
{'BusinessName': 'Howe and Co Fish and Chips - Van 17',
 'BusinessType': 'Mobile caterer',
 'LocalAuthorityName': 'Greenwich',
 'RatingValue': 5,
 '_id': ObjectId('666fa2bb635b43e663fb632c'),
 'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'BusinessName': 'Lumbini Grocery Ltd T/A Al-Iman',
 'BusinessType': 'Retailers - other',
 'LocalAuthorityName': 'Greenwich',
 'RatingValue': 5,
 '_id': ObjectId('666fa2bb635b43e663fb636c'),
 'geocode': {'latitude': 51.4871632, 'longitude': 0.0916256},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 5}}
{'BusinessName': 'Plumstead Manor Nursery',
 'BusinessType': 'Caring Premises',
 'LocalAuthorityName': 'Greenwich',
 'RatingValue': 5,
 '_id': ObjectId('666fa2bb635b43e663fb6368'),
 'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}}
{'BusinessName': 'Iceland',
 'BusinessType': 'Retailers - supermarkets/hypermarkets',
 'LocalAuthorityName': 'Greenwich',
 'RatingValue': 5,
 '_id': ObjectId('666fa2bb635b43e663fb631c'),
 'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}
{'BusinessName': 'Volunteer',
 'BusinessType': 'Pub/bar/nightclub',
 'LocalAuthorityName': 'Greenwich',
 'RatingValue': 5,
 '_id': ObjectId('666fa2bb635b43e663fb6350'),
 'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

In [52]:
# Convert result to Pandas DataFrame

lat_long_doc = list(establishments.find(query, fields))
lat_long_df = pd.DataFrame(lat_long_doc)

# Display the number of rows in the DataFrame
rows = lat_long_df.shape[0]
print(f'Number of rows: {rows}')

# Display the first 10 rows of the DataFrame
lat_long_df.head(10)

Number of rows: 87

,_id,BusinessName,BusinessType,RatingValue,LocalAuthorityName,scores,geocode
0,666fa2bb635b43e663fb6307,TIWA N TIWA African Restaurant Ltd,Restaurant/Cafe/Canteen,5,Greenwich,"{'Hygiene': 5, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0927429, 'latitude': 51.4870351}"
1,666fa2bb635b43e663fb631c,Iceland,Retailers - supermarkets/hypermarkets,5,Greenwich,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0924199968576431, 'latitude': ..."
2,666fa2bb635b43e663fb632c,Howe and Co Fish and Chips - Van 17,Mobile caterer,5,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0925370007753372, 'latitude': ..."
3,666fa2bb635b43e663fb6350,Volunteer,Pub/bar/nightclub,5,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.09208, 'latitude': 51.4873437}"
4,666fa2bb635b43e663fb6368,Plumstead Manor Nursery,Caring Premises,5,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0859939977526665, 'latitude': ..."
5,666fa2bb635b43e663fb636c,Lumbini Grocery Ltd T/A Al-Iman,Retailers - other,5,Greenwich,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0916256, 'latitude': 51.4871632}"
6,666fa2bb635b43e663fb6373,Atlantic Fish Bar,Takeaway/sandwich shop,5,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0912164, 'latitude': 51.4867296}"
7,666fa2bb635b43e663fb6387,Tesco,Retailers - supermarkets/hypermarkets,5,Greenwich,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...","{'longitude': 0.0912820026278496, 'latitude': ..."
8,666fa2bb635b43e663fb638a,Greggs,Takeaway/sandwich shop,5,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0912820026278496, 'latitude': ..."
9,666fa2bb635b43e663fb63ad,Abbi Wines,Retailers - other,5,Greenwich,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...","{'longitude': 0.0908895, 'latitude': 51.4871401}"

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [ ]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

# Print the number of documents in the result

# Print the first 10 results

In [ ]:
# Convert the result to a Pandas DataFrame

# Display the number of rows in the DataFrame

# Display the first 10 rows of the DataFrame